# Generated by Django 5.1.7 on 2025-03-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweet_dislikes_tweet_img_url_tweet_likes_tweet_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
