# Generated by Django 5.1.7 on 2025-03-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_alter_tweet_img_url_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img_url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
