# Generated by Django 5.1.7 on 2025-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_alter_tweet_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='img_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
